version: '3.1'

services:
  db:
    image: postgres
    container_name: cm-test-database
    ports:
      - '127.0.0.1:${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - cm-db-volume:/var/lib/postgresql/data
volumes:
  cm-db-volume:
